### PR TITLE
Add yank tasks

### LINKED ISSUE #54: There should be a rake task to yank from packagecloud
We can easily release to packagecloud but we can't easily yank.

### PR DESCRIPTION
**Pull request by tonydewan**
Yanking packages from packagecloud is hard right now, since it requires manually removing packages in the web interface. (fixes #54.) We were already yanking as a part of releasing, so it was mostly figured out. This makes yanking a first-class action. Specifically:

- Add individual yank tasks for each architecture, to match existing release tasks
- Add global yank task (`package:yank`)
- Update release task to use new yank tasks and to be more clear in messaging what it is doing

Worth considering adding:

- the `package:yank` task could take an argument for which version to yank that defaults to `VERSION`, making the task way more useful.

### CODE REVIEW

**Comment by mediocretes** [comment]
This seems like it will always yank the current version, which is usually not what I actually want to do.  Maybe make `VERSION = ENV['VERSION'] || Instrumentald::VERSION` or something?

**Comment by tonydewan** [comment]
@mediocretes yep, that's why I said the thing at the bottom of the description. 😏  I will add version selection posthaste!

**Comment by mediocretes** [comment]
What I suggested was dumb and would ruin everything, FYI.

**Comment by tonydewan** [comment]
@mediocretes only kinda! Changing the global constant to be that would be bad, but we can respect the env var within the yank commands only. That's what that last commit does. Now you can do:

```
rake package:yank version=0.0.6
```

**Pull request merged**
