### PR TITLE
better mongodb configuration

### PR DESCRIPTION
**Pull request by mediocretes**
mongodb uses reasonable server name tags, and also has reasonable multi-server configuration.

let's take advantage of that!

### CODE REVIEW

**Comment by tonydewan** [comment]
:+1:

**Comment by janxious** [comment]
What is the thing this was outputting and what is the thing it now outputs?

**Comment by mediocretes** [comment]
https://instrumentalapp.com/graphs/7105?resolution=60&duration=1800&start=0

It was outputting mongodb.<mongo hostname>.mongodb.<repl_status>.<metric>

It now outputs mongodb.<mongo hostname>.<metric>

**Comment by tonydewan** [comment]
Before:

```
mongodb.<mongo hostname>.<everything before the first ':' in your connection string>.<repl_status>.<metric>
```

Now:
```
mongodb.<mongo hostname>.<metric>
```

**Pull request merged**
