### PR TITLE
Add a development readme

### PR DESCRIPTION
**Pull request by tonydewan**

### CODE REVIEW

**Comment by janxious** [comment]
I think there are two development pieces. You have outlined well the work on telegraf, but not the work on instrumentald itself.

**Comment by tonydewan** [comment]
I agree! My main goal here was to get that bit about telegraf out of the main readme. Now that that's achieved, I will write more!

**Comment by janxious** [comment]
👍 

side question: are we locked into beta 3 of telegraf? That's what it seems like when I run:

```
rake package:build_telegraf
```

**Comment by tonydewan** [comment]
I think we are locked into whatever version telegraf master builds.

**Comment by tonydewan** [comment]
@janxious I added some content. Let me know if you think it's a good enough start. It's not comprehensive, but may be enough of a stub that we can merge it with the plan to add more later.

**Comment by janxious** [comment]
:shipit:

**Pull request merged**
