### PR TITLE
Fix macOS build

### PR DESCRIPTION
**Pull request by tonydewan**
https://github.com/influxdata/telegraf/pull/1571 removed building for darwin from the telegraf build script, which our build script relies on. This updates our build script to build for darwin using `make` directly IF you're on a darwin machine.

It still assumes that you have a working Go environment and telegraf is checked out, which is a rough edge we might want to take care of at some point.

This PR also includes updated telegraf binaries, since we haven't done that in awhile and it happened as a side effect of making this change. I expect them to explicitly updated during releases once we reach 1.0, but figured it was fine to do this way now.

### CODE REVIEW

**Comment by janxious** [comment]
Does this need to include any changes to install/build instructions?

**Comment by tonydewan** [comment]
@janxious great point. Updated!

**Comment by janxious** [comment]
My testing thus far is inconclusive. The same behavior for master as this. I have not tested the builds themselves, so maybe the differences are there. Certainly this seems to function correctly!

**Comment by tonydewan** [comment]
@janxious, to test:

Run the following in this branch and master.
```
rake package:build_telegraf
```

In master, you should see the following git status:
```
	modified:   lib/telegraf/amd64/telegraf
	modified:   lib/telegraf/i386/telegraf
```

In this branch, you *should* see:
```
	modified:   lib/telegraf/amd64/telegraf
	modified:   lib/telegraf/i386/telegraf
	modified:   lib/telegraf/i386/telegraf
```

**Comment by janxious** [comment]
I feel like that *should* list is not correct?

**Comment by janxious** [comment]
Should this "go get telegraf" or whatever the thing is to make telegraf exist on the system during `rake package:build_telegraf`?

I `rm -rf $GO_PATH/src/influxdata/telegraf` and then the package step died. The build for OSX still did its thing.

**Comment by tonydewan** [comment]
Hmm. Something should! `script/setup` probably?

**Comment by janxious** [comment]
I think if you follow the instructions  in development.md, you get to a fine place to do more. I say let's shap it. This does the things it purports to, so 👍

**Pull request merged**
