### PR TITLE
Stop packaging as a rubygem

### PR DESCRIPTION
**Pull request by tonydewan**
We decided not to deliver `instrumentald` via rubygems (like we did with `instrumental_tools`). This PR purports to implement that decision.

~~This is marked as `HOLD` because, depending on how successful we are at setting up a homebrew formula, we may want to fall back to relying on rubygems for delivering ISD for macOS.~~

Review ~~still~~ welcome and desired, especially from @mediocretes.

### CODE REVIEW

**Comment by mediocretes** [comment]
Looks pretty reasonable.  Like you said, depending on how home-brew goes, we may need this for mac.

**Comment by tonydewan** [comment]
Given #44, I have removed the HOLD flag and consider this mergeable.

**Comment by janxious** [comment]
There is an entry [here](https://github.com/Instrumental/instrumentald/blob/master/INSTALL.md#rubygems) that probably needs to be delorted

**Comment by tonydewan** [comment]
@janxious delorted.

**Comment by janxious** [comment]
The rake tasks seem to be gone for building the gem, which is correct. I was not able to find evidence of additional gems that had been published under alternate names. 👍

**Pull request merged**
